# Nome
spring.application.name=waze-saude

# Configurações de conexão com o banco H2
spring.datasource.url=jdbc:h2:mem:wazedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Spring cria as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita a interface visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console